openapi: '3.0.3'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://127.0.0.1:8000

paths:
  /submitData/{id}:
      parameters: 
      - name: id
        in: path
        required: true
        description: Get map information by id                
        schema: 
          type: string  
      get:            
        responses:
          '200': 
            {description: map to be returned,
            content: {
              {application/json: {
                add_time: string,
                user_id: int,
                images: [
                  {
                    id: int,
                    title: string
                  }
                ],
                raw_data: {
                title: string,
                other_titles: string,
                connect: string,
                coords: {
                  latitude: string,
                  longitude: string,
                  height: string
                        },
                level: {
                  winter: string,
                  summer: string,
                  autumn: string,
                  spring: string
                        }
                        },
                id: int,
                status: string
                    }
                
                    }
                  }
                }




