openapi: '3.0.3'
info:
  title: API map db crud
  version: '1.0'
servers:
  - url: https://127.0.0.1:8000


components:
  schemas:
    images: {
      type: object,
      properties: {
        id: {type: integer},
        title: {type: string}
      }
    }
    raw_data: {
      type: object,
        properties: {
        title: {type: string},
        other_titles: {type: string},
        connect: {type: string},
        coords: {properties: 
                {
                  latitude: {type: string},
                  longitude: {type: string},
                  height: {type: string}
                },
                },
        level: {properties:
                {          
                  winter: {type: string},
                  summer: {type: string},
                  autumn: {type: string},
                  spring: {type: string}
                        }
                      }
                  }
    }

paths:
  /submitData/{id}:
      parameters: 
      - name: id
        in: path
        required: true
        description: Get map information by id                
        schema: 
          type: string  
      get:            
        responses:
          '200': 
            {description: map to be returned,
            content: {
              {application/json: {
                add_time: string,
                user_id: int,
                images: [
                  {
                    id: int,
                    title: string
                  }
                ],
                raw_data: {
                title: string,
                other_titles: string,
                connect: string,
                coords: {
                  latitude: string,
                  longitude: string,
                  height: string
                        },
                level: {
                  winter: string,
                  summer: string,
                  autumn: string,
                  spring: string
                        }
                        },
                id: int,
                status: string
                    }
                
                    }
                  }
                }

  /submitData/{id}/:
    patch:
      description: post map data in db
      parameters: 
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: data
          in: header
          required: true
          content: {
            application/json: {
              schema: {
                type: object,
                properties: {
                  add_time: {type string},
                  raw_data: {/components/schemas/raw_data},
                  user: {type int}, 
                  images: {/components/schemas/images}            
                }
              }

            }}
      responses:
        '200':
          description: OK



