"""status_added

Revision ID: 05426ec80045
Revises: ae8114855e58
Create Date: 2024-08-21 09:27:02.461426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05426ec80045'
down_revision: Union[str, None] = 'ae8114855e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_object')
    op.create_table('map_object',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('other_titles', sa.VARCHAR(), nullable=True),
    sa.Column('connect', sa.VARCHAR(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('coords', sa.VARCHAR(), nullable=False),  
    sa.Column('level', sa.VARCHAR(), nullable=True),
    sa.Column('images', sa.BINARY(), nullable=True), 
    sa.Column('status', sa.VARCHAR(), nullable=False)      
    # ### end Alembic commands ###
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_object')
    op.create_table('map_object',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('other_titles', sa.VARCHAR(), nullable=True),
    sa.Column('connect', sa.VARCHAR(), nullable=True),
    sa.Column('add_time', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('coords', sa.VARCHAR(), nullable=False),
    sa.Column('level', sa.VARCHAR(), nullable=True),
    sa.Column('images', sa.NUMERIC(), nullable=True)
    )
    # ### end Alembic commands ###
