"""map_object_intit

Revision ID: 136a2550779d
Revises: 19aacf4bc105
Create Date: 2024-08-20 10:22:19.237528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136a2550779d'
down_revision: Union[str, None] = '19aacf4bc105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_object',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('other_titles', sa.VARCHAR(), nullable=True),
    sa.Column('connect', sa.VARCHAR(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=False),
    sa.Column('user', sa.PickleType(), nullable=True),
    sa.Column('coords', sa.PickleType(), nullable=True),  
    sa.Column('level', sa.PickleType(), nullable=False),
    sa.Column('images', [sa.BINARY()], nullable=True)   
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_object')

    # ### end Alembic commands ###
