"""correction1

Revision ID: 19aacf4bc105
Revises: 64bc9d01519a
Create Date: 2024-08-19 14:18:28.495077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19aacf4bc105'
down_revision: Union[str, None] = '64bc9d01519a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users', sa.Column('id', sa.Integer(), nullable=False), 
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.drop_table('user')
    # ### end Alembic commands ###
