"""imagelist

Revision ID: 3c85f87a9a8a
Revises: 05426ec80045
Create Date: 2024-08-21 14:13:16.969848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c85f87a9a8a'
down_revision: Union[str, None] = '05426ec80045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_object')
    op.create_table('map_object',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('other_titles', sa.VARCHAR(), nullable=True),
    sa.Column('connect', sa.VARCHAR(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('coords', sa.VARCHAR(), nullable=False),  
    sa.Column('level', sa.VARCHAR(), nullable=True),
    sa.Column('images', sa.VARCHAR(), nullable=True), 
    sa.Column('status', sa.VARCHAR(), nullable=False)   
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_object')
    op.create_table('map_object',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('other_titles', sa.VARCHAR(), nullable=True),
    sa.Column('connect', sa.VARCHAR(), nullable=True),
    sa.Column('add_time', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('coords', sa.VARCHAR(), nullable=False),
    sa.Column('level', sa.VARCHAR(), nullable=True),
    sa.Column('images', sa.BINARY(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False)
    )

    # ### end Alembic commands ###
