"""json_fields

Revision ID: 9f6130afd20f
Revises: 3c85f87a9a8a
Create Date: 2024-08-21 17:24:29.549899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f6130afd20f'
down_revision: Union[str, None] = '3c85f87a9a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_object')
    op.create_table('map_object',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('add_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True), 
    sa.Column('raw_data', sa.JSON(), nullable=True),     
    sa.Column('status', sa.VARCHAR(), nullable=False)   
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_object')
    op.create_table('map_object',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('other_titles', sa.VARCHAR(), nullable=True),
    sa.Column('connect', sa.VARCHAR(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('coords', sa.VARCHAR(), nullable=False),  
    sa.Column('level', sa.VARCHAR(), nullable=True),
    sa.Column('images', sa.VARCHAR(), nullable=True), 
    sa.Column('status', sa.VARCHAR(), nullable=False)   
    )

    # ### end Alembic commands ###
